export const SET_ALL_POKEMONS = "SET_ALL_POKEMONS";
export const SET_SEARCHED_POKEMON = "SET_SEARCHED_POKEMON";
export const CLEAR_SEARCHED_POKEMON = "CLEAR_SEARCHED_POKEMON";
export const FILTER_BY_TYPE_AND_ORIGIN = "FILTER_POKEMONS";
export const ORDER_CARDS = "ORDER_CARDS";
